<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Relief.Domain\Relief.Domain.csproj" />
    <ProjectReference Include="..\Relief.ServiceAbstraction\Relief.ServiceAbstraction.csproj" />
  </ItemGroup>


	<ItemGroup>
	  <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.3.25" />
	  <PackageReference Include="AWSSDK.S3" Version="4.0.19" />
	  <PackageReference Include="AWSSDK.SimpleEmailV2" Version="4.0.12.2" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.24" />
	  <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
	</ItemGroup>

</Project>
