// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Relief.Presistence.Data.DbContexts;

#nullable disable

namespace Relief.Presistence.Migrations
{
    [DbContext(typeof(ReliefAppDbContext))]
    [Migration("20260306010125_removing request status")]
    partial class removingrequeststatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Relief.Domain.Entities.Offers.JobOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CareHomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid?>("IndividualId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CareHomeId");

                    b.HasIndex("IndividualId");

                    b.ToTable("JobOffers");
                });

            modelBuilder.Entity("Relief.Domain.Entities.Offers.JobRequestItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JopRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JopRequestId");

                    b.HasIndex("ShiftId");

                    b.ToTable("JobRequestItems");
                });

            modelBuilder.Entity("Relief.Domain.Entities.Offers.JopRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JobOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("JobOfferId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PswId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JobOfferId");

                    b.HasIndex("JobOfferId1");

                    b.HasIndex("PswId");

                    b.ToTable("JopRequests");
                });

            modelBuilder.Entity("Relief.Domain.Entities.Offers.OfferShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedPswId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("AssignedPswId");

                    b.HasIndex("JobOfferId");

                    b.ToTable("OfferShifts");
                });

            modelBuilder.Entity("Relief.Domain.Entities.Users.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApartmentNumber")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Relief.Domain.Entities.Users.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthOfDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Insurance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Relief.Domain.Entities.Users.CareHomeUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessLicense")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaccinationPolicy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CareHomeUsers");
                });

            modelBuilder.Entity("Relief.Domain.Entities.Users.FileMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Relief.Domain.Entities.Users.IndividualCareHomeUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("IndividualUsers");
                });

            modelBuilder.Entity("Relief.Domain.Entities.Users.PswUser", b =>
                {
                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CVFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CriminalRecordFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FirstAidOrCPRFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ImmunizationRecordFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InsuranceFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsProfileCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ProofIdentityFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProofIdentityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PswCertificateFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("WorkStatus")
                        .HasColumnType("bit");

                    b.HasKey("ApplicationUserId");

                    b.HasIndex("CVFileId");

                    b.HasIndex("CriminalRecordFileId");

                    b.HasIndex("FirstAidOrCPRFileId");

                    b.HasIndex("ImmunizationRecordFileId");

                    b.HasIndex("InsuranceFileId");

                    b.HasIndex("ProofIdentityFileId");

                    b.HasIndex("PswCertificateFileId");

                    b.ToTable("PswUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Relief.Domain.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Relief.Domain.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relief.Domain.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Relief.Domain.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Relief.Domain.Entities.Offers.JobOffer", b =>
                {
                    b.HasOne("Relief.Domain.Entities.Users.CareHomeUser", "CareHomeUser")
                        .WithMany("JobOffers")
                        .HasForeignKey("CareHomeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Relief.Domain.Entities.Users.IndividualCareHomeUser", "IndividualCareHomeUser")
                        .WithMany("JobOffers")
                        .HasForeignKey("IndividualId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CareHomeUser");

                    b.Navigation("IndividualCareHomeUser");
                });

            modelBuilder.Entity("Relief.Domain.Entities.Offers.JobRequestItem", b =>
                {
                    b.HasOne("Relief.Domain.Entities.Offers.JopRequest", "JopRequest")
                        .WithMany("Items")
                        .HasForeignKey("JopRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relief.Domain.Entities.Offers.OfferShift", "OfferShift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JopRequest");

                    b.Navigation("OfferShift");
                });

            modelBuilder.Entity("Relief.Domain.Entities.Offers.JopRequest", b =>
                {
                    b.HasOne("Relief.Domain.Entities.Offers.JobOffer", "JobOffer")
                        .WithMany()
                        .HasForeignKey("JobOfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Relief.Domain.Entities.Offers.JobOffer", null)
                        .WithMany("JopRequests")
                        .HasForeignKey("JobOfferId1");

                    b.HasOne("Relief.Domain.Entities.Users.PswUser", "PswUser")
                        .WithMany("JobRequests")
                        .HasForeignKey("PswId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobOffer");

                    b.Navigation("PswUser");
                });

            modelBuilder.Entity("Relief.Domain.Entities.Offers.OfferShift", b =>
                {
                    b.HasOne("Relief.Domain.Entities.Users.PswUser", "AssignedPsw")
                        .WithMany()
                        .HasForeignKey("AssignedPswId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Relief.Domain.Entities.Offers.JobOffer", "JobOffer")
                        .WithMany("Shifts")
                        .HasForeignKey("JobOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedPsw");

                    b.Navigation("JobOffer");
                });

            modelBuilder.Entity("Relief.Domain.Entities.Users.ApplicationUser", b =>
                {
                    b.HasOne("Relief.Domain.Entities.Users.Address", "Address")
                        .WithOne("User")
                        .HasForeignKey("Relief.Domain.Entities.Users.ApplicationUser", "AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Relief.Domain.Entities.Users.CareHomeUser", b =>
                {
                    b.HasOne("Relief.Domain.Entities.Users.ApplicationUser", "ApplicationUser")
                        .WithOne("CareHomeUser")
                        .HasForeignKey("Relief.Domain.Entities.Users.CareHomeUser", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Relief.Domain.Entities.Users.IndividualCareHomeUser", b =>
                {
                    b.HasOne("Relief.Domain.Entities.Users.ApplicationUser", "ApplicationUser")
                        .WithOne("IndividualCareHomeUser")
                        .HasForeignKey("Relief.Domain.Entities.Users.IndividualCareHomeUser", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Relief.Domain.Entities.Users.PswUser", b =>
                {
                    b.HasOne("Relief.Domain.Entities.Users.ApplicationUser", "ApplicationUser")
                        .WithOne("PswUser")
                        .HasForeignKey("Relief.Domain.Entities.Users.PswUser", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relief.Domain.Entities.Users.FileMetadata", "CVFile")
                        .WithMany()
                        .HasForeignKey("CVFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Relief.Domain.Entities.Users.FileMetadata", "CriminalRecordFile")
                        .WithMany()
                        .HasForeignKey("CriminalRecordFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Relief.Domain.Entities.Users.FileMetadata", "FirstAidOrCPRFile")
                        .WithMany()
                        .HasForeignKey("FirstAidOrCPRFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Relief.Domain.Entities.Users.FileMetadata", "ImmunizationRecordFile")
                        .WithMany()
                        .HasForeignKey("ImmunizationRecordFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Relief.Domain.Entities.Users.FileMetadata", "InsuranceFile")
                        .WithMany()
                        .HasForeignKey("InsuranceFileId");

                    b.HasOne("Relief.Domain.Entities.Users.FileMetadata", "ProofIdentityFile")
                        .WithMany()
                        .HasForeignKey("ProofIdentityFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Relief.Domain.Entities.Users.FileMetadata", "PswCertificateFile")
                        .WithMany()
                        .HasForeignKey("PswCertificateFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationUser");

                    b.Navigation("CVFile");

                    b.Navigation("CriminalRecordFile");

                    b.Navigation("FirstAidOrCPRFile");

                    b.Navigation("ImmunizationRecordFile");

                    b.Navigation("InsuranceFile");

                    b.Navigation("ProofIdentityFile");

                    b.Navigation("PswCertificateFile");
                });

            modelBuilder.Entity("Relief.Domain.Entities.Offers.JobOffer", b =>
                {
                    b.Navigation("JopRequests");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("Relief.Domain.Entities.Offers.JopRequest", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Relief.Domain.Entities.Users.Address", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("Relief.Domain.Entities.Users.ApplicationUser", b =>
                {
                    b.Navigation("CareHomeUser");

                    b.Navigation("IndividualCareHomeUser");

                    b.Navigation("PswUser");
                });

            modelBuilder.Entity("Relief.Domain.Entities.Users.CareHomeUser", b =>
                {
                    b.Navigation("JobOffers");
                });

            modelBuilder.Entity("Relief.Domain.Entities.Users.IndividualCareHomeUser", b =>
                {
                    b.Navigation("JobOffers");
                });

            modelBuilder.Entity("Relief.Domain.Entities.Users.PswUser", b =>
                {
                    b.Navigation("JobRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
